name: pocketinvent
description: Application mobile de gestion de stock et de suivi des transactions de téléphones
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.6

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Backend & Auth
  supabase_flutter: ^2.5.0

  # OCR & Image
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.0.7

  # Apple Sign In
  sign_in_with_apple: ^7.0.1

  # Google Sign In
  google_sign_in: ^7.2.0

  # UI & Utils
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  flutter_dotenv: ^5.1.0

  # Export
  csv: ^6.0.0
  pdf: ^3.11.1
  path_provider: ^2.1.4
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
